# Handling Missing Values and Using `datetime` 

This lesson focuses on reviewing our basics with pandas and extending them to more advanced munging and cleaning.  Specifically, we will discuss how to load data files, work with missing values, use split-apply-combine, use string methods, and work with string and datetime objects.  By the end of this lesson you should feel confident doing basic exploratory data analysis using `pandas`. 

**OBJECTIVES**


- Drop missing values
- Replace missing values
- Impute missing values
- Use built in `.dt` methods
- Convert columns to `pd.datetime` datatype
- Work with `datetime` objects in pandas.

## Missing Values and Dates with `pandas`

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#what is the path to ufo.csv?
ufo_path = 'https://raw.githubusercontent.com/jfkoehler/nyu_bootcamp_spr26/refs/heads/main/data/ufo.csv'

##### `read_csv`

Now, using the path to the `ufo.csv` file, you can create a DataFrame by passing this filepath to the `read_csv` function.

In [3]:
#read in ufo data
ufo = pd.read_csv(ufo_path)

In [4]:
# look at first 2 rows
ufo.head(2)

          City Colors Reported Shape Reported State             Time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00

### Missing Values

Missing values are a common problem in data, whether this is because they are truly missing or there is confusion between the data encoding and the methods you read the data in using.

In [5]:
# re-examine ufo info
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80543 entries, 0 to 80542
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             80492 non-null  object
 1   Colors Reported  17034 non-null  object
 2   Shape Reported   72141 non-null  object
 3   State            80543 non-null  object
 4   Time             80543 non-null  object
dtypes: object(5)
memory usage: 3.1+ MB

In [6]:
# one-liner to count missing values

In [7]:
# drop missing values

In [8]:
# fill missing values

In [9]:
# replace missing values with most common value

In [10]:
#using fillna

In [11]:
# be careful with comparisons!!!

#### Problem

1. Read in the dataset `churn_missing.csv` in the data folder, assign to a variable `churn` below.

In [12]:
churn = pd.read_csv('https://raw.githubusercontent.com/jfkoehler/nyu_bootcamp_spr26/refs/heads/main/data/churn_missing.csv')

2. Are there any missing values?  What columns are they in and how many are there?

3. What do you think we should do about these?  Drop, replace, impute?

#### `datetime`

A special type of data for pandas are entities that can be considered as dates.  We can create a special datatype for these using `pd.to_datetime`, and access the functions of the `datetime` module as a result.

In [13]:
# read in the AAPL data
aapl = pd.read_csv('https://raw.githubusercontent.com/jfkoehler/nyu_bootcamp_spr26/refs/heads/main/data/AAPL.csv')
aapl.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  2005-04-25  5.212857  5.288571  5.158571  5.282857   3.522625  186615100
1  2005-04-26  5.254286  5.358572  5.160000  5.170000   3.447372  202626900
2  2005-04-27  5.127143  5.194286  5.072857  5.135714   3.424510  153472200
3  2005-04-28  5.184286  5.191429  5.034286  5.077143   3.385454  143776500
4  2005-04-29  5.164286  5.175714  5.031428  5.151429   3.434988  167907600

In [14]:
# convert to datetime -- problem for slack

In [15]:
# extract the month -- problem for slack

In [16]:
# extract the day -- problem for slack

In [17]:
# set date to be index of data -- together

In [18]:
# sort the index -- together

Once we have a `datetime` index we can use elements of the dates to select rows and slices of data based on date ranges.

In [19]:
# select 2019

In [20]:
# read back in using parse_dates = True and index_col = 0
aapl = pd.read_csv('https://raw.githubusercontent.com/jfkoehler/nyu_bootcamp_spr26/refs/heads/main/data/AAPL.csv', parse_dates=True, index_col=0)
aapl.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3523 entries, 2005-04-25 to 2019-04-23
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       3523 non-null   float64
 1   High       3523 non-null   float64
 2   Low        3523 non-null   float64
 3   Close      3523 non-null   float64
 4   Adj Close  3523 non-null   float64
 5   Volume     3523 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 192.7 KB

In [21]:
from datetime import datetime

In [22]:
# what time is it?

In [23]:
# how much time has passed?

#### More with timestamps

- Date times: A specific date and time with timezone support. Similar to datetime.datetime from the standard library.

- Time deltas: An absolute time duration. Similar to datetime.timedelta from the standard library.

- Time spans: A span of time defined by a point in time and its associated frequency.

- Date offsets: A relative time duration that respects calendar arithmetic.

In [24]:
# create a pd.Timedelta

In [25]:
# shift a date by 3 months

##### Problems

1. Return to the ufo data and convert the Time column to a datetime object.

2. Set the Time column as the index column of the data.

3. Sort it

4. Create a new dataframe with ufo sightings since January 1, 1999